Comment out logging because of macros issue
[error] /Users/jpark/shoe_backend/src/main/scala/CassandraClient.scala:58: macro implementation not found: info
[error] (the most common reason for that is that you cannot use macro implementations in the same compilation run that defines them)
[error]     logger.info(s"CREATE KEYSPACE IF NOT EXISTS $keyspace")
[error]                ^
[error] /Users/jpark/shoe_backend/src/main/scala/WebServer.scala:72: macro implementation not found: error
[error] (the most common reason for that is that you cannot use macro implementations in the same compilation run that defines them)
[error]         logger.error(s"Request to $uri could not be handled normally")
[error]                     ^
[error] two errors found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 18 s, completed May 2, 2018, 6:39:54 PM